### ISSUE TITLE
Error loading module

### ISSUE THREAD

**Issue by lmaule** [avinor/terraform-azurerm-log-analytics#1]
Terraform version: 0.11.8
azurerm: 1.29

I have been having issues loading this module in my terraform file. I receive the following error message from the terminal in visual studio code;

Error downloading modules: Error loading modules: module workspace: Error parsing .terraform/modules/40978c9b861d54d1b03e93c65a8c9718/avinor-terraform-azurerm-log-analytics-6ba481c/main.tf: At 7:14: Unknown token: 7:14 IDENT var.resource_group_name

I can see what the error is referencing to but not sure how to solve this error.

**Comment by lmaule** [comment]
Tired 0.2.0 and 1.0.0 but both throw the same error.

**Comment by tesharp** [comment]
This is due to the terraform version. This module requires at least 0.12 of terraform. Tried to set that in the terraform block in `main.tf` but it seems like terraform 0.11 fails parsing file and never reads that block..

Solution is to upgrade terraform
